# Generated by Django 3.0.7 on 2020-07-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200620_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_pic.jpg', upload_to='profile_pics'),
        ),
    ]
