# Generated by Django 3.0.7 on 2020-06-25 11:45

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200625_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
